### ISSUE TITLE
bash init.sh: no such file or directory

### ISSUE THREAD

**Issue by uwhuan** [milannair/LetsMeet#20]
## Summary
I'm trying to install your project following the steps in the users' documentation. In step 3, it says to run bash init.sh but there is no such file in your root directory

## Steps to Reproduce

1. cd to the root directory of letsmeet

2. run bash init.sh in git bash

3.

## Expected Behavior
run init.sh

## Actual Behavior
no init.sh file

## Device Information

Windows
node.js -v: 12.16.3

**Comment by milannair** [comment]
It seems that our init.sh file got deleted, it has been re-uploaded to the repository. Run `git pull` to update your local project with the remote changes
